# Generated by Django 6.0.4 on 2026-05-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_insight_pontosgamificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='despersonalizacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='exaustao_emocional',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='realizacao_profissional',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ansiedade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='burnout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='depressao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='estresse',
            field=models.IntegerField(default=0),
        ),
    ]
